@startuml
title WarmHouse Membership Management Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class User {
  +Int id
  +String name
  +String email
  +void register()
  +void login()
}

class SensorDto {
  +Int id
  +Int user_id
  +String value
  +String type
  +Date startDate
  +Date endDate
  +void activate()
  +void cancel()
}