@startuml
title WarmHouse Device-Control-Component Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

entity DeviceControlModule {
    void Create()
    void Delete()
    void Get()
}

class Sensor {
  +Int id
  +Int user_id
  +String name
  +String value
  +String type
  +String status
  +Date last_updated
  +Date created_at
}

DeviceControlModule "1" -- "0..*" Sensor : includes

@enduml
