@startuml

title Warm House Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of Warm House system")
Person(admin, "Administrator", "An administrator who connects sensors to the system")

System(WarmHouseSystem, "Warm House System", "System managing sensors and provides tempertature info to users")

Rel(user, WarmHouseSystem, "Regulates the temperature")
Rel(user, WarmHouseSystem, "Requests temperature data")
Rel(admin, WarmHouseSystem,"Maintains the sensors in the system by visiting the user")

@enduml
