@startuml
title Warm House Containers Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of Warm House system")
Person(admin, "Administrator", "An administrator who connects sensors to the system")

System(WarmHouseSystem, "Warm House System", "System managing sensors and provides tempertature info to users")

Container_Boundary(WarmHouseSystem, "Warm House System") {
  Container(frontend, "Front-end", "ui", "Handles user interactions")
  Container(apiGateway, "ExternalAPI Gateway", "Api")
  Container(AuthRegService, "Auth/Registration Service", "Handles authentication and authorization")
  Container(DeviceService, "Device Service", "Handles devices")
  Container_Ext(SensorsService, "Sensors Service", "Manages sensors work")
  ContainerDb(Database, "Database", "PostgreSQL", "Stores user data and sensors' states")
}

Rel(user, frontend, "Uses the system")
Rel(admin, frontend,"Manages the system")
Rel(frontend,apiGateway,"RESTful API")
Rel(apiGateway,AuthRegService,"Calls business logic")
Rel(apiGateway,DeviceService,"Calls business logic")
Rel(AuthRegService,Database,"Reads/Writes user data")
Rel(DeviceService,Database,"Reads/Writes user data")
Rel(DeviceService,SensorsService,"Manages physical devices")
@enduml
