services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - smarthome-network
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smarthome"]
      interval: 5s
      timeout: 15s
      retries: 10
      start_period: 30s

  temperature-api:
    build:
      context: ../temperature-api
      dockerfile: Dockerfile
    container_name: temperature-api
    ports:
      - "8081:8081"
    networks:
      - smarthome-network

  sensors-telemetry-service:
    build:
      context: ./sensors-telemetry-service
      dockerfile: Dockerfile
    container_name: sensors-telemetry-service
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - smarthome-network
    depends_on:
      postgres:
        condition: service_healthy

  device-control-service:
    build:
      context: ./device-control-service
      dockerfile: Dockerfile
    container_name: device-control-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8083:8083"
    restart: unless-stopped
    networks:
      - smarthome-network
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build:
      context: ../smart-home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - temperature-api_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge
